/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_skystardust_inputmethodblocker_IMENativeAccess */

#ifndef _Included_com_github_skystardust_inputmethodblocker_IMENativeAccess
#define _Included_com_github_skystardust_inputmethodblocker_IMENativeAccess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_skystardust_inputmethodblocker_IMENativeAccess
 * Method:    activeIME
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_skystardust_inputmethodblocker_IMENativeAccess_activeIME
  (JNIEnv *, jclass);

/*
 * Class:     com_github_skystardust_inputmethodblocker_IMENativeAccess
 * Method:    inactiveIME
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_skystardust_inputmethodblocker_IMENativeAccess_inactiveIME
  (JNIEnv *, jclass);

/*
 * Class:     com_github_skystardust_inputmethodblocker_IMENativeAccess
 * Method:    getIMEStatus
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_github_skystardust_inputmethodblocker_IMENativeAccess_getIMEStatus
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
