/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_skystardust_InputMethodBlocker_NativeInterface */

#ifndef _Included_com_github_skystardust_InputMethodBlocker_NativeInterface
#define _Included_com_github_skystardust_InputMethodBlocker_NativeInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_skystardust_InputMethodBlocker_NativeInterface
 * Method:    activeInputMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_skystardust_InputMethodBlocker_NativeInterface_activeInputMethod
  (JNIEnv *, jclass);

/*
 * Class:     com_github_skystardust_InputMethodBlocker_NativeInterface
 * Method:    inactiveInputMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_skystardust_InputMethodBlocker_NativeInterface_inactiveInputMethod
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
